# Generated by Django 6.0.6 on 2026-06-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether an editor has approved this article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of editorial approval.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Editor who approved the article.', limit_choices_to={'role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='Journalist or editor who wrote the article.', limit_choices_to={'role__in': ['journalist', 'editor']}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full body text of the article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Affiliated publisher, or null for an independent article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsapp.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Headline of the article.', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Articles included in this newsletter edition.', related_name='newsletters', to='newsapp.article'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(help_text='Journalist or editor responsible for this newsletter.', limit_choices_to={'role__in': ['journalist', 'editor']}, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.TextField(help_text='Short summary shown in newsletter listings.'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(help_text='Name of the newsletter edition.', max_length=500),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Editors affiliated with this publisher.', limit_choices_to={'role': 'editor'}, related_name='publishing_as_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, help_text='Journalists affiliated with this publisher.', limit_choices_to={'role': 'journalist'}, related_name='publishing_as_journalist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Display name of the publishing organisation.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], default='reader', help_text='Determines site‑wide permissions for this user.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, help_text='Journalists this reader follows.', related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, help_text='Publishers this reader follows.', related_name='subscribers', to='newsapp.publisher'),
        ),
    ]
